In [1]:
import numpy as np

## Datatypes and Attributes

In [3]:
# numpy main datatype in ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0, 3.2],
     [4.2, 5, 6.2]])

a3 = np.array([[[1,2,3],
               [4,5,6,],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5. , 6.2]])

In [7]:
a1.shape


(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
# df3 = pd.DataFrame(a3)
df

0    1    2
0  1.0  2.0  3.2
1  4.2  5.0  6.2

## Creating Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype


dtype('int64')

In [20]:
ones = np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)

In [27]:
range_array 

array([0, 2, 4, 6, 8])

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.01955428, 0.58490677, 0.19573547],
       [0.92580563, 0.21584036, 0.81182576],
       [0.42243395, 0.5183087 , 0.88401933],
       [0.03046569, 0.28275552, 0.95081058],
       [0.64084097, 0.63913829, 0.7543603 ]])

In [29]:
random_array_2.dtype

dtype('float64')

In [30]:
type(random_array_2)

numpy.ndarray

In [31]:
random_array_2.shape

(5, 3)

In [33]:
#pseudo random number
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [38]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [39]:
# Create massive array Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [40]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5. , 6.2]])

In [41]:
a2.shape

(2, 3)

In [42]:
a2_reshape = a2.reshape(2, 3, 1)

In [43]:
a2_reshape

array([[[1. ],
        [2. ],
        [3.2]],

       [[4.2],
        [5. ],
        [6.2]]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 22.4,  25.6,  28.8]],

       [[ 42. ,  46.2,  50.4],
        [ 65. ,  70. ,  75. ],
        [ 99.2, 105.4, 111.6]]])

In [47]:
# transpose = Switch axes
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

<img src="panda.png" />

In [50]:
# Turn an image into a numpy array
from matplotlib.image import imread

panda = imread("panda.png")
type(panda)

numpy.ndarray

In [51]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [54]:
panda[:100]


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0