In [1]:
import numpy as np

## DataTypes attributes

In [2]:
# numpy data type as ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
             [4,5,6.5]])
a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2, 3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 5, 9, 9, 1],
       [3, 0, 3, 7, 4],
       [5, 2, 2, 0, 1]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.01260531, 0.9030448 , 0.93757961],
       [0.70927537, 0.31521977, 0.99264847],
       [0.28571646, 0.97803168, 0.27809589],
       [0.7336234 , 0.15238574, 0.10402523],
       [0.77175184, 0.23335777, 0.4242892 ]])

In [25]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.75638899, 0.4515734 , 0.6085627 ],
       [0.13629814, 0.55815857, 0.93438922],
       [0.55293241, 0.68263621, 0.48510876],
       [0.34882345, 0.41252979, 0.88985904],
       [0.20355805, 0.21729912, 0.20115602]])

In [27]:
# pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed()
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.8849624 , 0.59855506, 0.47848537],
       [0.13870228, 0.10299838, 0.06361228],
       [0.47168499, 0.63555909, 0.90994472],
       [0.35211631, 0.94788026, 0.70937992],
       [0.86901839, 0.87591858, 0.64043487]])

In [29]:
random_array_4.shape

(5, 3)

## 3. Viewing array and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
a2[1]

array([4. , 5. , 6.5])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[5, 6, 1, 7, 8],
         [4, 7, 3, 9, 5],
         [0, 2, 7, 7, 8],
         [1, 0, 1, 6, 7]],

        [[0, 8, 5, 7, 8],
         [1, 7, 0, 2, 3],
         [1, 3, 5, 3, 9],
         [2, 3, 0, 3, 0]],

        [[7, 4, 3, 0, 8],
         [8, 5, 0, 2, 7],
         [8, 7, 0, 1, 1],
         [2, 4, 0, 5, 7]]],


       [[[5, 6, 5, 8, 7],
         [0, 6, 7, 9, 3],
         [1, 4, 2, 3, 3],
         [0, 7, 8, 4, 7]],

        [[4, 6, 1, 7, 3],
         [5, 8, 5, 3, 8],
         [9, 1, 3, 0, 5],
         [8, 1, 4, 2, 1]],

        [[9, 7, 9, 1, 8],
         [5, 9, 4, 6, 0],
         [8, 3, 6, 8, 2],
         [2, 0, 6, 8, 2]]]])

In [43]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
# Get the first 4 numers of the inner most arrays
a4[:, :, :, :4]

array([[[[5, 6, 1, 7],
         [4, 7, 3, 9],
         [0, 2, 7, 7],
         [1, 0, 1, 6]],

        [[0, 8, 5, 7],
         [1, 7, 0, 2],
         [1, 3, 5, 3],
         [2, 3, 0, 3]],

        [[7, 4, 3, 0],
         [8, 5, 0, 2],
         [8, 7, 0, 1],
         [2, 4, 0, 5]]],


       [[[5, 6, 5, 8],
         [0, 6, 7, 9],
         [1, 4, 2, 3],
         [0, 7, 8, 4]],

        [[4, 6, 1, 7],
         [5, 8, 5, 3],
         [9, 1, 3, 0],
         [8, 1, 4, 2]],

        [[9, 7, 9, 1],
         [5, 9, 4, 6],
         [8, 3, 6, 8],
         [2, 0, 6, 8]]]])

## 4. Manipulating and comparing data

### Arithmetic

In [45]:
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [47]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1-ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
## how to reshape a2 to be compatible with a3
## Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [54]:
a2/ a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [55]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [58]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
a1 + ones

array([2., 3., 4.])

In [60]:
np.add(a1, ones)

array([2., 3., 4.])

In [61]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [62]:
a1 / 2

array([0.5, 1. , 1.5])

In [63]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [64]:
a2 / 2

array([[0.5 , 1.  , 1.65],
       [2.  , 2.5 , 3.25]])

In [65]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [67]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggrigation means perform the same operation on a number of things

In [66]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [67]:
sum(a1)

6

In [68]:
np.sum(a1)

6

use python methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy's methonds
on numpy datatype (`np.sum()`).

In [71]:
# Creating a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [ ]:
massive_array[:100]