In [1]:
import numpy as np

## DataTypes attributes

In [2]:
# numpy data type as ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
             [4,5,6.5]])
a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 0, 5, 5, 3],
       [4, 0, 0, 6, 5],
       [2, 1, 6, 1, 1]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.59063942, 0.82779936, 0.62410388],
       [0.19808986, 0.7485129 , 0.50458677],
       [0.67388776, 0.27228897, 0.32402665],
       [0.42451604, 0.90726066, 0.41443754],
       [0.60355504, 0.87605878, 0.62646852]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.96405245, 0.31443412, 0.80965441],
       [0.00640876, 0.318746  , 0.7615355 ],
       [0.84675587, 0.10726127, 0.88207285],
       [0.0685395 , 0.62618274, 0.49235665],
       [0.34498756, 0.68507565, 0.06893761]])

In [34]:
# pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [35]:
np.random.seed()
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.43349245, 0.32758129, 0.04814629],
       [0.51901911, 0.8687072 , 0.27492191],
       [0.76521557, 0.48622131, 0.92053509],
       [0.71410016, 0.4446269 , 0.76454604],
       [0.87491627, 0.0314111 , 0.82382957]])

In [36]:
random_array_4.shape

(5, 3)

## 3. Viewing array and matrices

In [37]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1

array([1, 2, 3])

In [39]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a1[0]

1

In [42]:
a2[0]

array([1. , 2. , 3.3])

In [43]:
a3.shape

(2, 3, 3)

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a2[1]

array([4. , 5. , 6.5])