In [1]:
import numpy as np

## DataTypes attributes

In [2]:
# numpy data type as ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
             [4,5,6.5]])
a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2, 3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 3, 5, 6, 2],
       [1, 8, 5, 5, 9],
       [9, 2, 9, 1, 7]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.66584994, 0.56639777, 0.1700974 ],
       [0.98945103, 0.67182648, 0.25172354],
       [0.29134629, 0.8573162 , 0.79247203],
       [0.0942624 , 0.89922452, 0.49536106],
       [0.44004455, 0.25095756, 0.87568055]])

In [25]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.65341356, 0.88454345, 0.89508393],
       [0.93961974, 0.36131074, 0.38718318],
       [0.90846097, 0.19403849, 0.837282  ],
       [0.90901222, 0.85726535, 0.92476129],
       [0.05159883, 0.89944701, 0.53441572]])

In [27]:
# pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed()
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.93461187, 0.92531762, 0.31611654],
       [0.96046122, 0.33173538, 0.42037816],
       [0.54914874, 0.61822194, 0.96407721],
       [0.79954607, 0.23819579, 0.3518489 ],
       [0.88569617, 0.80955827, 0.75394916]])

In [29]:
random_array_4.shape

(5, 3)

## 3. Viewing array and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
a2[1]

array([4. , 5. , 6.5])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 1, 4, 8, 7],
         [4, 8, 9, 9, 7],
         [9, 2, 2, 1, 3],
         [2, 7, 1, 1, 1]],

        [[4, 6, 9, 2, 2],
         [3, 4, 1, 6, 0],
         [4, 0, 9, 9, 1],
         [2, 2, 6, 5, 9]],

        [[4, 0, 4, 3, 8],
         [5, 7, 0, 8, 6],
         [9, 5, 8, 8, 7],
         [8, 5, 6, 6, 5]]],


       [[[4, 0, 6, 3, 5],
         [3, 3, 8, 6, 1],
         [4, 1, 1, 0, 9],
         [8, 3, 3, 2, 5]],

        [[8, 3, 2, 8, 2],
         [9, 4, 9, 8, 3],
         [0, 7, 3, 1, 1],
         [8, 4, 0, 3, 5]],

        [[6, 5, 1, 8, 8],
         [5, 7, 7, 6, 5],
         [6, 7, 0, 8, 7],
         [6, 0, 7, 2, 0]]]])

In [43]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
# Get the first 4 numers of the inner most arrays
a4[:, :, :, :4]

array([[[[8, 1, 4, 8],
         [4, 8, 9, 9],
         [9, 2, 2, 1],
         [2, 7, 1, 1]],

        [[4, 6, 9, 2],
         [3, 4, 1, 6],
         [4, 0, 9, 9],
         [2, 2, 6, 5]],

        [[4, 0, 4, 3],
         [5, 7, 0, 8],
         [9, 5, 8, 8],
         [8, 5, 6, 6]]],


       [[[4, 0, 6, 3],
         [3, 3, 8, 6],
         [4, 1, 1, 0],
         [8, 3, 3, 2]],

        [[8, 3, 2, 8],
         [9, 4, 9, 8],
         [0, 7, 3, 1],
         [8, 4, 0, 3]],

        [[6, 5, 1, 8],
         [5, 7, 7, 6],
         [6, 7, 0, 8],
         [6, 0, 7, 2]]]])

## 4. Manipulating and comparing data

### Arithmetic

In [45]:
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [47]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1-ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
## how to reshape a2 to be compatible with a3
## Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2/ a1

In [ ]:
a2//a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [54]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
np.add(a1, ones)

array([2., 3., 4.])

In [57]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [58]:
a1 / 2

array([0.5, 1. , 1.5])

In [59]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [60]:
a2 / 2

array([[0.5 , 1.  , 1.65],
       [2.  , 2.5 , 3.25]])

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [62]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggrigation means perform the same operation on a number of things

In [63]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [64]:
sum(a1)

6

In [65]:
np.sum(a1)

6

use python methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy's methonds
on numpy datatype (`np.sum()`).

In [66]:
# Creating a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [67]:
massive_array[:10]

array([0.34511417, 0.12491141, 0.26782768, 0.48028918, 0.89001381,
       0.05854744, 0.66249343, 0.45812159, 0.85438366, 0.49321377])

In [68]:
%timeit sum(massive_array) # python's sum
%timeit np.sum(massive_array) # Numpy's np.sum()

12.4 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
81.9 µs ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [70]:
np.mean(a2)

3.6333333333333333

In [71]:
np.max(a2)

6.5

In [72]:
np.min(a2)

1.0

In [73]:
# Standard deviation is a measure of how spread out a group of number is from the main
np.std(a2)

1.8226964152656422

In [74]:
# Varience is a measure of the average degree to which each number is different
# Higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [75]:
# standard deviation is square root of variant
np.sqrt(np.var(a2))

1.8226964152656422

In [76]:
# Demo of std and var
high_var_array =  np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [77]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [78]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)