In [1]:
import numpy as np

## DataTypes attributes

In [2]:
# numpy data type as ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
             [4,5,6.5]])
a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2, 3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 7, 2, 6, 5],
       [1, 9, 6, 1, 2],
       [6, 4, 3, 9, 5]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.978233  , 0.41617839, 0.24545884],
       [0.46819919, 0.72736605, 0.19114472],
       [0.94471017, 0.48968574, 0.1937475 ],
       [0.11030453, 0.44104608, 0.98570404],
       [0.11249184, 0.46552198, 0.99424643]])

In [25]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.36669112, 0.41238019, 0.22472217],
       [0.23512511, 0.160507  , 0.88044314],
       [0.02539581, 0.57991069, 0.7529945 ],
       [0.5446781 , 0.10477878, 0.70557215],
       [0.84092622, 0.36132994, 0.74962745]])

In [27]:
# pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed()
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.13111184, 0.58594375, 0.05148696],
       [0.88337693, 0.15295129, 0.66014855],
       [0.34616737, 0.98532096, 0.96330353],
       [0.04022569, 0.55150634, 0.91139972],
       [0.57984515, 0.92914454, 0.38258813]])

In [29]:
random_array_4.shape

(5, 3)

## 3. Viewing array and matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
a2[1]

array([4. , 5. , 6.5])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 7, 2, 6, 6],
         [3, 4, 4, 1, 4],
         [9, 5, 1, 0, 0],
         [2, 4, 3, 1, 6]],

        [[3, 5, 7, 0, 8],
         [5, 6, 3, 7, 6],
         [6, 3, 1, 9, 5],
         [6, 3, 7, 9, 5]],

        [[0, 4, 6, 9, 2],
         [7, 5, 1, 3, 8],
         [7, 7, 8, 6, 1],
         [1, 5, 9, 3, 5]]],


       [[[7, 4, 8, 5, 9],
         [4, 5, 4, 9, 8],
         [5, 7, 6, 9, 2],
         [7, 8, 7, 7, 6]],

        [[0, 1, 4, 8, 5],
         [1, 7, 6, 6, 0],
         [5, 4, 8, 2, 6],
         [6, 3, 6, 6, 2]],

        [[3, 0, 8, 9, 2],
         [9, 9, 9, 0, 2],
         [3, 5, 1, 7, 2],
         [5, 2, 2, 5, 8]]]])

In [43]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
# Get the first 4 numers of the inner most arrays
a4[:, :, :, :4]

array([[[[2, 7, 2, 6],
         [3, 4, 4, 1],
         [9, 5, 1, 0],
         [2, 4, 3, 1]],

        [[3, 5, 7, 0],
         [5, 6, 3, 7],
         [6, 3, 1, 9],
         [6, 3, 7, 9]],

        [[0, 4, 6, 9],
         [7, 5, 1, 3],
         [7, 7, 8, 6],
         [1, 5, 9, 3]]],


       [[[7, 4, 8, 5],
         [4, 5, 4, 9],
         [5, 7, 6, 9],
         [7, 8, 7, 7]],

        [[0, 1, 4, 8],
         [1, 7, 6, 6],
         [5, 4, 8, 2],
         [6, 3, 6, 6]],

        [[3, 0, 8, 9],
         [9, 9, 9, 0],
         [3, 5, 1, 7],
         [5, 2, 2, 5]]]])

## 4. Manipulating and comparing data

### Arithmetic

In [45]:
a1

array([1, 2, 3])

In [46]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [47]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1-ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [51]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
## how to reshape a2 to be compatible with a3
## Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [54]:
a1 / ones

array([1., 2., 3.])

In [55]:
a2/ a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [56]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])